<a href="https://colab.research.google.com/github/Edebo/expresso-dsn/blob/master/expresso2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
from sklearn.preprocessing import MinMaxScaler




In [2]:
train_url = "https://raw.githubusercontent.com/Edebo/expresso-dsn/master/Train.csv"

train_data = pd.read_csv(train_url)

train_data.head()

user_id       REGION  ... FREQ_TOP_PACK  CHURN
0  dcf68cc2fb515ccad7d8b9b3bd80ee2a4b270063  SAINT-LOUIS  ...          35.0      0
1  71c44b5ba328db5c4192a80f7cf8f244d9350ed0          NaN  ...          22.0      0
2  ce46411b1526c94f20a383b8cb188f8d27f82a0a  TAMBACOUNDA  ...           3.0      0
3  f467cdb6669818373c26c2bad44e01ba66f97d21       FATICK  ...           3.0      0
4  ec45e1a1888a32b5dcce0954cfec20c6e037db31       FATICK  ...           NaN      0

[5 rows x 19 columns]

In [3]:
train_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 400000 entries, 0 to 399999
Data columns (total 19 columns):
 #   Column          Non-Null Count   Dtype  
---  ------          --------------   -----  
 0   user_id         400000 non-null  object 
 1   REGION          242480 non-null  object 
 2   TENURE          400000 non-null  object 
 3   MONTANT         259723 non-null  float64
 4   FREQUENCE_RECH  259723 non-null  float64
 5   REVENUE         265337 non-null  float64
 6   ARPU_SEGMENT    265337 non-null  float64
 7   FREQUENCE       265337 non-null  float64
 8   DATA_VOLUME     203146 non-null  float64
 9   ON_NET          254181 non-null  float64
 10  ORANGE          233683 non-null  float64
 11  TIGO            160614 non-null  float64
 12  ZONE1           31690 non-null   float64
 13  ZONE2           25513 non-null   float64
 14  MRG             400000 non-null  object 
 15  REGULARITY      400000 non-null  int64  
 16  TOP_PACK        232671 non-null  object 
 17  FREQ_TOP_P

In [4]:
x= train_data.isnull().sum()
x

user_id                0
REGION            157520
TENURE                 0
MONTANT           140277
FREQUENCE_RECH    140277
REVENUE           134663
ARPU_SEGMENT      134663
FREQUENCE         134663
DATA_VOLUME       196854
ON_NET            145819
ORANGE            166317
TIGO              239386
ZONE1             368310
ZONE2             374487
MRG                    0
REGULARITY             0
TOP_PACK          167329
FREQ_TOP_PACK     167329
CHURN                  0
dtype: int64

In [5]:
train=train_data.drop(["ZONE1","ZONE2","MRG"],axis=1)
len(train)

400000

In [9]:
#train["REGION"].dropna()
#train = train[train['REGION'].notna()]

In [7]:

ka=train["REGION"][train["REGION"].notnull()]
train["REGION"].fillna(ka.mode()[0],inplace=True)
train.fillna(train["TIGO"].mean(),inplace=True)
train.fillna(train["DATA_VOLUME"].mean(),inplace=True)
train.fillna(train["ON_NET"].mean(),inplace=True)
train.fillna(train["ORANGE"].mean(),inplace=True)
train.fillna(train["TOP_PACK"].mode(),inplace=True)
train.fillna(train["FREQ_TOP_PACK"].mean(),inplace=True)
train.fillna(train["MONTANT"].mean(),inplace=True)
train.fillna(train["FREQUENCE_RECH"].mean(),inplace=True)
ka


0         SAINT-LOUIS
1               DAKAR
2         TAMBACOUNDA
3              FATICK
4              FATICK
             ...     
399995    TAMBACOUNDA
399996          DAKAR
399997          DAKAR
399998          DAKAR
399999          DAKAR
Name: REGION, Length: 400000, dtype: object

In [8]:
train.isnull().sum()

user_id           0
REGION            0
TENURE            0
MONTANT           0
FREQUENCE_RECH    0
REVENUE           0
ARPU_SEGMENT      0
FREQUENCE         0
DATA_VOLUME       0
ON_NET            0
ORANGE            0
TIGO              0
REGULARITY        0
TOP_PACK          0
FREQ_TOP_PACK     0
CHURN             0
dtype: int64

In [9]:
len(train)

400000

In [10]:
train["TENURE"].value_counts()

K > 24 month     379439
I 18-21 month      8312
H 15-18 month      4858
G 12-15 month      2788
J 21-24 month      2325
F 9-12 month       1771
E 6-9 month         359
D 3-6 month         148
Name: TENURE, dtype: int64

In [11]:
train["TENURE"].unique()

array(['K > 24 month', 'H 15-18 month', 'G 12-15 month', 'J 21-24 month',
       'I 18-21 month', 'E 6-9 month', 'F 9-12 month', 'D 3-6 month'],
      dtype=object)

In [12]:
from sklearn.preprocessing import LabelEncoder
#converting tenure categorical to numerical
tenure = LabelEncoder()
train["TENURE"] = tenure.fit_transform(train["TENURE"])
train["TENURE"].value_counts()

7    379439
5      8312
4      4858
3      2788
6      2325
2      1771
1       359
0       148
Name: TENURE, dtype: int64

In [13]:
region = LabelEncoder()
train["REGION"] = region.fit_transform(train["REGION"])
train["REGION"].value_counts()

0     253037
12     33374
9      22125
7      18513
4      18042
1      12576
11     10273
3       8181
6       7204
2       6638
8       5255
13      4012
10       589
5        181
Name: REGION, dtype: int64

In [14]:
top_pack = LabelEncoder()
train["TOP_PACK"] = top_pack.fit_transform(train["TOP_PACK"].astype(str))
train["TOP_PACK"].value_counts()

4      167329
16      58675
85      28387
39      21661
26      15590
        ...  
51          1
45          1
24          1
19          1
111         1
Name: TOP_PACK, Length: 112, dtype: int64

In [16]:
train.head()

user_id  REGION  ...  FREQ_TOP_PACK  CHURN
0  dcf68cc2fb515ccad7d8b9b3bd80ee2a4b270063       9  ...      35.000000      0
1  71c44b5ba328db5c4192a80f7cf8f244d9350ed0       0  ...      22.000000      0
2  ce46411b1526c94f20a383b8cb188f8d27f82a0a      11  ...       3.000000      0
3  f467cdb6669818373c26c2bad44e01ba66f97d21       2  ...       3.000000      0
4  ec45e1a1888a32b5dcce0954cfec20c6e037db31       2  ...      23.134608      0

[5 rows x 16 columns]

In [17]:
data = train.drop(["user_id"],axis=1)
data.reset_index(drop=True, inplace=True)
data

REGION  TENURE       MONTANT  ...  TOP_PACK  FREQ_TOP_PACK  CHURN
0            9       7  17000.000000  ...        16      35.000000      0
1            0       7   4300.000000  ...        26      22.000000      0
2           11       7   1500.000000  ...        16       3.000000      0
3            2       7   1500.000000  ...        85       3.000000      0
4            2       7     23.134608  ...         4      23.134608      0
...        ...     ...           ...  ...       ...            ...    ...
399995      11       7    700.000000  ...        16       1.000000      0
399996       0       7     23.134608  ...         4      23.134608      0
399997       0       7    700.000000  ...        26       3.000000      0
399998       0       7     23.134608  ...         4      23.134608      1
399999       0       7     23.134608  ...         4      23.134608      0

[400000 rows x 15 columns]

In [18]:
data_feature = data.drop(["CHURN"],axis=1) 
target= data["CHURN"]
target.value_counts()

0    325156
1     74844
Name: CHURN, dtype: int64

In [21]:
# Seaborn visualization library
import seaborn as sns
#sns.pairplot(train)

/usr/local/lib/python3.6/dist-packages/statsmodels/tools/_testing.py:19: FutureWarning: pandas.util.testing is deprecated. Use the functions in the public API at pandas.testing instead.
  import pandas.util.testing as tm


In [19]:
categorical = data[["REGION","TENURE","TOP_PACK"]]
numerical = data.drop(["REGION","TENURE","TOP_PACK","CHURN"],axis=1)
data_feature = data.drop(["CHURN"],axis=1)
data_feature

REGION  TENURE       MONTANT  ...  REGULARITY  TOP_PACK  FREQ_TOP_PACK
0            9       7  17000.000000  ...          62        16      35.000000
1            0       7   4300.000000  ...          40        26      22.000000
2           11       7   1500.000000  ...          32        16       3.000000
3            2       7   1500.000000  ...          18        85       3.000000
4            2       7     23.134608  ...          50         4      23.134608
...        ...     ...           ...  ...         ...       ...            ...
399995      11       7    700.000000  ...          46        16       1.000000
399996       0       7     23.134608  ...          14         4      23.134608
399997       0       7    700.000000  ...          15        26       3.000000
399998       0       7     23.134608  ...           5         4      23.134608
399999       0       7     23.134608  ...           1         4      23.134608

[400000 rows x 14 columns]

In [20]:
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
feature = scaler.fit_transform(numerical)
feature = pd.DataFrame(feature, columns=numerical.columns)
feature["REGION"] = categorical["REGION"]
feature["TENURE"] = categorical["TENURE"]
feature["TOP_PACK"] = categorical["REGION"]

In [21]:
len(feature)

400000

In [22]:
feature.columns

Index(['MONTANT', 'FREQUENCE_RECH', 'REVENUE', 'ARPU_SEGMENT', 'FREQUENCE',
       'DATA_VOLUME', 'ON_NET', 'ORANGE', 'TIGO', 'REGULARITY',
       'FREQ_TOP_PACK', 'REGION', 'TENURE', 'TOP_PACK'],
      dtype='object')

#Logistic Regression
#k-Nearest Neighbors
#Support Vector Machine
#SDG
#RandomForestClassifier

In [23]:
from sklearn.model_selection import cross_val_score
from sklearn.metrics import confusion_matrix
from sklearn.metrics import precision_score, recall_score
from sklearn.model_selection import cross_val_predict



In [24]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(feature, target,test_size=0.2, random_state=42,stratify=target)


##**Logistic regression**

In [25]:
#Logistic regression
from sklearn.linear_model import LogisticRegression
logreg = LogisticRegression(max_iter = 10000,random_state=42)
log_score =cross_val_score(logreg, feature,target, cv=5, scoring="accuracy")

#print("Accuracy: {} ,std:{}".format(log_score.mean(),log_score.std()))
log_score


array([0.86585  , 0.8642875, 0.86235  , 0.8632375, 0.8656375])

In [26]:
logreg.fit(feature,target)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=10000,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=42, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [27]:
log_pred = cross_val_predict(logreg,feature, target, cv=5)
log_pred

conf_mat = confusion_matrix(target, log_pred)
conf_mat


array([[296025,  29131],
       [ 25160,  49684]])

In [35]:
precision_score(target, log_pred)

0.6303876165704498

In [29]:
recall_score(target,log_pred)

0.6638341082785527

In [30]:
from sklearn.metrics import f1_score

f1_score(target,log_pred)

0.6466786846198401

##**k-Nearest Neigbour**

In [32]:
#knearestneighbor
from sklearn.neighbors import KNeighborsClassifier

knn = KNeighborsClassifier(n_neighbors=3)

knn_score =cross_val_score(knn, feature,target, cv=5, scoring="accuracy")

print("Accuracy: {} ,std:{}".format(log_score.mean(),log_score.std()))



Accuracy: 0.8642724999999999 ,std:0.001350495279517859


In [33]:
knn.fit(feature,target)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=3, p=2,
                     weights='uniform')

In [34]:
knn_pred = cross_val_predict(logreg,feature, target, cv=5)
knn_pred

conf_mat = confusion_matrix(target, knn_pred)
conf_mat


array([[296025,  29131],
       [ 25160,  49684]])

In [36]:
precision_score(target, knn_pred)

0.6303876165704498

In [37]:
recall_score(target,knn_pred)

0.6638341082785527

In [38]:
from sklearn.metrics import f1_score

f1_score(target,knn_pred)

0.6466786846198401

##**SDG**


In [42]:
#sdg 
from sklearn.linear_model import SGDClassifier
sgd = SGDClassifier(random_state=42)








In [43]:
sgd_score =cross_val_score(sgd, feature,target, cv=5, scoring="accuracy")

print("Accuracy: {} ,std:{}".format(sgd_score.mean(),sgd_score.std()))

Accuracy: 0.855495 ,std:0.0064118279374917615


In [44]:
sgd.fit(feature,target)

SGDClassifier(alpha=0.0001, average=False, class_weight=None,
              early_stopping=False, epsilon=0.1, eta0=0.0, fit_intercept=True,
              l1_ratio=0.15, learning_rate='optimal', loss='hinge',
              max_iter=1000, n_iter_no_change=5, n_jobs=None, penalty='l2',
              power_t=0.5, random_state=42, shuffle=True, tol=0.001,
              validation_fraction=0.1, verbose=0, warm_start=False)

In [45]:
sgd_pred = cross_val_predict(sgd,feature, target, cv=5)

conf_mat = confusion_matrix(target, sgd_pred)
conf_mat


array([[288234,  36922],
       [ 20880,  53964]])

In [46]:
precision_score(target, sgd_pred)

0.5937548137226856

In [47]:
recall_score(target,sgd_pred)

0.721019721019721

In [48]:
from sklearn.metrics import f1_score

f1_score(target,sgd_pred)

0.65122790080251

#RandomForest Classifier

In [49]:
#Randoforestclassifier
from sklearn.ensemble import RandomForestClassifier

rfc = RandomForestClassifier(n_estimators = 100,random_state=42)
rfc_score =cross_val_score(rfc, feature,target, cv=5, scoring="accuracy")

print("Accuracy: {} ,std:{}".format(rfc_score.mean(),rfc_score.std()))

Accuracy: 0.8678325000000001 ,std:0.001719422141302131


In [50]:
rfc.fit(feature,target)

RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=None, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=100,
                       n_jobs=None, oob_score=False, random_state=42, verbose=0,
                       warm_start=False)

In [51]:
rfc_pred = cross_val_predict(rfc,feature, target, cv=5)

conf_mat = confusion_matrix(target, rfc_pred)
conf_mat 

array([[301172,  23984],
       [ 28883,  45961]])

In [52]:
precision_score(target, rfc_pred)

0.657102008721138

In [53]:
recall_score(target,rfc_pred)

0.6140906418684197

In [54]:
from sklearn.metrics import f1_score

f1_score(target,rfc_pred)

0.6348686709625732

# ROC Area under curve

In [55]:
from sklearn.metrics import roc_auc_score

#logistic regression
log_auc =roc_auc_score(target, log_pred)

#knn
knn_auc =roc_auc_score(target, knn_pred)

# sgd
sgd_auc =roc_auc_score(target,sgd_pred)

#randomforest

rfc_auc =roc_auc_score(target,rfc_pred)

print(log_auc,knn_auc,sgd_auc,rfc_auc)


0.7871216328645653 0.7871216328645653 0.8037340359825567 0.77016456215996


SGD has more accuracy than the rest.SO SGD will be used for the predicting the test

In [56]:
test =pd.read_csv("https://raw.githubusercontent.com/Edebo/expresso-dsn/master/Test.csv")
test.head()

user_id  ... FREQ_TOP_PACK
0  af900d87e73b7ff6509d2203df4704a98aa5f2a6  ...           NaN
1  5335efd940280b82143272275637d1e65d37eadb  ...           NaN
2  a581f4fa08677c26f83f643248c667e241043086  ...          17.0
3  64f67177d0775262b8087a9e2e3b8061b6324ae6  ...           3.0
4  0d6009a4594c4be22449b8d9cc01a0bcea98faea  ...          65.0

[5 rows x 18 columns]

In [57]:
len(test)

100000

In [58]:
test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 18 columns):
 #   Column          Non-Null Count   Dtype  
---  ------          --------------   -----  
 0   user_id         100000 non-null  object 
 1   REGION          60707 non-null   object 
 2   TENURE          100000 non-null  object 
 3   MONTANT         65049 non-null   float64
 4   FREQUENCE_RECH  65049 non-null   float64
 5   REVENUE         66510 non-null   float64
 6   ARPU_SEGMENT    66510 non-null   float64
 7   FREQUENCE       66510 non-null   float64
 8   DATA_VOLUME     50662 non-null   float64
 9   ON_NET          63617 non-null   float64
 10  ORANGE          58800 non-null   float64
 11  TIGO            40212 non-null   float64
 12  ZONE1           7680 non-null    float64
 13  ZONE2           6422 non-null    float64
 14  MRG             100000 non-null  object 
 15  REGULARITY      100000 non-null  int64  
 16  TOP_PACK        58297 non-null   object 
 17  FREQ_TOP_PA

In [59]:
test.isnull().sum()

user_id               0
REGION            39293
TENURE                0
MONTANT           34951
FREQUENCE_RECH    34951
REVENUE           33490
ARPU_SEGMENT      33490
FREQUENCE         33490
DATA_VOLUME       49338
ON_NET            36383
ORANGE            41200
TIGO              59788
ZONE1             92320
ZONE2             93578
MRG                   0
REGULARITY            0
TOP_PACK          41703
FREQ_TOP_PACK     41703
dtype: int64

In [60]:
test["REGION"].value_counts()

DAKAR          23998
THIES           8301
SAINT-LOUIS     5657
LOUGA           4616
KAOLACK         4542
DIOURBEL        3041
TAMBACOUNDA     2596
KAFFRINE        1940
KOLDA           1775
FATICK          1656
MATAM           1411
ZIGUINCHOR      1006
SEDHIOU          126
KEDOUGOU          42
Name: REGION, dtype: int64

In [61]:
test["REGION"].unique()

array([nan, 'DAKAR', 'KAFFRINE', 'KAOLACK', 'DIOURBEL', 'KOLDA', 'THIES',
       'TAMBACOUNDA', 'LOUGA', 'SAINT-LOUIS', 'MATAM', 'FATICK',
       'ZIGUINCHOR', 'KEDOUGOU', 'SEDHIOU'], dtype=object)

In [62]:

test = test.drop(["ZONE1","ZONE2","MRG"],axis=1)


In [63]:
test["REGION"].value_counts()

DAKAR          23998
THIES           8301
SAINT-LOUIS     5657
LOUGA           4616
KAOLACK         4542
DIOURBEL        3041
TAMBACOUNDA     2596
KAFFRINE        1940
KOLDA           1775
FATICK          1656
MATAM           1411
ZIGUINCHOR      1006
SEDHIOU          126
KEDOUGOU          42
Name: REGION, dtype: int64

In [64]:
ts=test["REGION"][test["REGION"].notnull()]

test["REGION"].fillna(ts.mode()[0],inplace=True)

In [65]:
test["REGION"].value_counts()

DAKAR          63291
THIES           8301
SAINT-LOUIS     5657
LOUGA           4616
KAOLACK         4542
DIOURBEL        3041
TAMBACOUNDA     2596
KAFFRINE        1940
KOLDA           1775
FATICK          1656
MATAM           1411
ZIGUINCHOR      1006
SEDHIOU          126
KEDOUGOU          42
Name: REGION, dtype: int64

In [66]:
test["REGION"].unique()

array(['DAKAR', 'KAFFRINE', 'KAOLACK', 'DIOURBEL', 'KOLDA', 'THIES',
       'TAMBACOUNDA', 'LOUGA', 'SAINT-LOUIS', 'MATAM', 'FATICK',
       'ZIGUINCHOR', 'KEDOUGOU', 'SEDHIOU'], dtype=object)

In [67]:
test.fillna(test["TIGO"].mean(),inplace=True)
test.fillna(test["REGION"].mode(),inplace=True)
test.fillna(test["DATA_VOLUME"].mean(),inplace=True)
test.fillna(test["ON_NET"].mean(),inplace=True)
test.fillna(test["ORANGE"].mean(),inplace=True)
test.fillna(test["TOP_PACK"].mode(),inplace=True)
test.fillna(test["FREQ_TOP_PACK"].mean(),inplace=True)
test.fillna(test["MONTANT"].mean(),inplace=True)
test.fillna(test["FREQUENCE_RECH"].mean(),inplace=True)

ts

3              DAKAR
4              DAKAR
6           KAFFRINE
8              DAKAR
10             DAKAR
            ...     
99994        KAOLACK
99995          LOUGA
99996    TAMBACOUNDA
99998          THIES
99999          MATAM
Name: REGION, Length: 60707, dtype: object

In [68]:

#converting tenure categorical to numerical
tenure = LabelEncoder()
test["TENURE"] = tenure.fit_transform(test["TENURE"])
#encoding region
region = LabelEncoder()
test["REGION"] = region.fit_transform(test["REGION"])

#top pack
top_pack = LabelEncoder()
test["TOP_PACK"] = top_pack.fit_transform(test["TOP_PACK"].astype(str))



In [69]:

categorical = test[["REGION","TENURE","TOP_PACK"]]
numerical = test.drop(["REGION","TENURE","TOP_PACK","user_id"],axis=1)


In [70]:
numerical.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 11 columns):
 #   Column          Non-Null Count   Dtype  
---  ------          --------------   -----  
 0   MONTANT         100000 non-null  float64
 1   FREQUENCE_RECH  100000 non-null  float64
 2   REVENUE         100000 non-null  float64
 3   ARPU_SEGMENT    100000 non-null  float64
 4   FREQUENCE       100000 non-null  float64
 5   DATA_VOLUME     100000 non-null  float64
 6   ON_NET          100000 non-null  float64
 7   ORANGE          100000 non-null  float64
 8   TIGO            100000 non-null  float64
 9   REGULARITY      100000 non-null  int64  
 10  FREQ_TOP_PACK   100000 non-null  float64
dtypes: float64(10), int64(1)
memory usage: 8.4 MB


In [71]:

scaler = MinMaxScaler()
test_feature = scaler.fit_transform(numerical)
test_feature = pd.DataFrame(test_feature, columns=numerical.columns)
test_feature["REGION"] = categorical["REGION"]
test_feature["TENURE"] = categorical["TENURE"]
test_feature["TOP_PACK"] = categorical["REGION"]

  

In [72]:
# clean_test = clean_data(test)
# encoded= encode_col(clean_test)
# cat_num = split_cat_num(encoded)[0]
# test_feature = scale_data(cat_num[0],cat_num[1])
test_feature.columns



Index(['MONTANT', 'FREQUENCE_RECH', 'REVENUE', 'ARPU_SEGMENT', 'FREQUENCE',
       'DATA_VOLUME', 'ON_NET', 'ORANGE', 'TIGO', 'REGULARITY',
       'FREQ_TOP_PACK', 'REGION', 'TENURE', 'TOP_PACK'],
      dtype='object')

In [73]:
#predicting

test_sgd_pred = sgd.predict(test_feature)
test_sgd_pred



array([1, 0, 0, ..., 0, 0, 0])

In [75]:
len(test_sgd_pred)

100000

In [76]:
churn = pd.Series(test_sgd_pred,name="CHURN")

In [78]:
result = pd.concat([test["user_id"],churn],axis=1)

In [79]:
result

user_id  CHURN
0      af900d87e73b7ff6509d2203df4704a98aa5f2a6      1
1      5335efd940280b82143272275637d1e65d37eadb      0
2      a581f4fa08677c26f83f643248c667e241043086      0
3      64f67177d0775262b8087a9e2e3b8061b6324ae6      0
4      0d6009a4594c4be22449b8d9cc01a0bcea98faea      0
...                                         ...    ...
99995  c6bcb3336795a18eb6c0bc7e19078a0704ef4d7e      0
99996  a44b4e44dc70115ed5bf971ebb4193dd536e87f0      0
99997  a2f84faffbc995bd0e2d726fa4ffdb93f11646ed      0
99998  afa76e894df4201fc77eb714de7d1f262299611a      0
99999  c08a2d84b87c1f5d4bb318114f508b77aa8e2663      0

[100000 rows x 2 columns]

In [82]:
from google.colab import drive
drive.mount('drive')


Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3aietf%3awg%3aoauth%3a2.0%3aoob&scope=email%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdocs.test%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive.photos.readonly%20https%3a%2f%2fwww.googleapis.com%2fauth%2fpeopleapi.readonly&response_type=code

Enter your authorization code:
··········
Mounted at drive


In [85]:
result.to_csv("drive/My Drive/adebowaleakande_submission.csv",index=False)